# Generated by Django 5.2 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_user_home_hide_unreleased"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="average_ratings",
            field=models.BooleanField(
                default=False,
                help_text="Use rating averages for unrated TV shows and seasons",
            ),
        ),
    ]
